### Makefile.inc --- LtxPkg configuration

## Copyright (C) 2009 Didier Verna

## Author:        Didier Verna <didier@lrde.epita.fr>
## Maintainer:    Didier Verna <didier@lrde.epita.fr>
## Created:       Thu Sep 10 21:41:42 2009
## Last Revision: Thu Sep 10 21:41:56 2009


### Commentary:

## Contents management by FCM version 0.1.


### Code:

TEXMFDIR = ${HOME}/.texmf

### Makefile.inc ends here
