### Makefile.inc --- LtxPkg configuration

## Copyright (C) 2009, 2017 Didier Verna

## Author: Didier Verna <didier@didierverna.net>

## This file is part of DoX.

## DoX may be distributed and/or modified under the conditions of the LaTeX
## Project Public License, either version 1.3 of this license or (at your
## option) any later version.  The latest version of this license is in
## http://www.latex-project.org/lppl.txt and version 1.3 or later is part of
## all distributions of LaTeX version 2005/12/01 or later.

## DoX consists of the files listed in the file `README.md'.


### Commentary:


### Code:

TEXMFDIR  := ${HOME}/.texmf
AUCTEXDIR := ${HOME}/etc/auctex

### Makefile.inc ends here
